### ISSUE TITLE
[BUG] screen functionality broke fcitx5 candidate window

### ISSUE THREAD

**Issue by name-snrl** [FedeDP/Clightd#110]
**NOTE:** Please try to upgrade Clight if not running on latest release, before reporting a bug!

**Clight version the issue has been seen with:**
> Current version: 4.10-

**Used distribution:**
> NixOS

**Describe the bug**
https://github.com/fcitx/fcitx5/issues/897, but I'm not sure if this can be fixed here, maybe the problem is in the wlroots implementation

**Expected behavior**
candidate window doesn't disappear

**To Reproduce**
https://github.com/fcitx/fcitx5/issues/897

Please attach a Clight [verbose log](https://github.com/FedeDP/Clight/wiki/FAQ#where-is-clight-log) too!

[clight.log](https://github.com/FedeDP/Clight/files/14016621/clight.log)

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue! 
I think the issue might actually belong to https://github.com/FedeDP/Clightd.
Which version of Clightd are you running?
I will move this to the Clightd repo btw!

**Comment by FedeDP** [comment]
I am going to check my `screen` impl agains eg: https://git.sr.ht/~emersion/grim/tree/master/item/main.c.
Perhaps i missed something in the cleanup phase? 

Anyway, you are saying that if you disable `screen` feature in Clight, everything works fine, right?

**Comment by name-snrl** [comment]
> Anyway, you are saying that if you disable `screen` feature in Clight, everything works fine, right?

Yes, that is correct. I'm also going to open an issue in sway tonight.

**Comment by name-snrl** [comment]
> Which version of Clightd are you running?

Current version: 5.8-

**Comment by FedeDP** [comment]
I can't see anything wrong in my impl compared to `grim`; can you try to use `grim` to take a screenshot and see if it triggers the issue?
Thank you very much btw!

**Comment by name-snrl** [comment]
> if it triggers the issue?

lol, yes, it does

**Comment by FedeDP** [comment]
:rofl: i assume it is not a bug with the client implementation then; perhaps it is a bug on `wlroots` side?

**Comment by name-snrl** [comment]
Yeah, now I'm off to sway or wlroots, need to check hyprland. Thank for this investigation.
