### ISSUE TITLE
clightd[9025]: /dev/video0: Permission denied

### ISSUE THREAD

**Issue by Taijian** [FedeDP/Clightd#12]
I run clight-git (and thus also clightd-git and ddcutil) on Arch. Lately, clight has stopped working and reports in it's log that:

{./modules/bus.c:308}	capture_frames_brightness(): Operation not permitted

clightd says: /dev/video0: Permission denied

I'm kinda stumped, because I thought that clightd runs as root and thus really shouldn't run into any permission issues? What am I doing wrong?

**Comment by FedeDP** [comment]
Hi! Thanks for your feedback!
Is your user in "video" group?
Can you paste here output of `ls -l /dev/video0` and `echo $UID` ?

Recently i decided to let clightd run as root but immediately drop root privileges, running as normal user and gaining privileges again only when needed.
But i already saw a bug with this; so i may revert this feature.

Note that i'm nearing release 3.0 of both clightd and clight; i plan to make a stable package available on aur afterwards, this way users should not notice these kind of breaks :)

EDIT: dropped the feature on devel branch.

**Comment by Taijian** [comment]
[gunnar@alien-arch ~]$ ls -l /dev/video0
crw-rw----+ 1 root video 81, 0  4. Nov 11:28 /dev/video0
[gunnar@alien-arch ~]$ groups
lp wheel rfkill games network video audio storage input vboxusers plugdev adbusers gunnar

**Comment by FedeDP** [comment]
`echo $UID` ?

EDIT: Unfortunately i hardcoded `static const uid_t unprivileged = 1000;`, ie: if your user has a different UID, "1000" won't be in video group probably, as it refers to another (possibly nonexistent) user.
This is the your issue, i guess.

**Comment by Taijian** [comment]
Yeah, my $UID is 1026, so that my be the issue. UID 1000 is not assigned on my system.

**Comment by FedeDP** [comment]
Easiest and fastest solution is to clone clightd, go into src/utils/privilege.c and change "1000" to "1026" at line 3.
Then "make" and "sudo make install".

It will be fixed as soon as i merge devel branch to master (before next release).
I'm sorry for the inconvenience.

**Comment by Taijian** [comment]
Hey, THANK YOU for making a cool tool for all of us to use and enjoy for free. I don't think you need to apologize to me at all :). And finding and fixing bugs is always good, so happy to help!

**Comment by Taijian** [comment]
Can confirm, though:

    sed -i 's/1000/1026/' src/utils/privilege.c

in the PKGBUILD did indeed fix the issue.

**Comment by FedeDP** [comment]
> Hey, THANK YOU for making a cool tool for all of us to use and enjoy for free. I don't think you need to apologize to me at all :)

Thanks for the kind words! :) I'm glad you like it!  
Nice to hear you are able to continue using it!
