### ISSUE TITLE
Manual brightness configuration

### ISSUE THREAD

**Issue by vivien** [FedeDP/Clightd#17]
Clight provides a nice backlight abstraction with smooth transitions, thus one might legitimately want to use it to configure the brightness manually. This would ditch the need for non-standard tools such as brightnessctl, Xorg-specific xbacklight or scripting `/sys/class/backlight`.

For this purpose we'd need a new bus API method (do not mind the following method names too much as they are yet to be defined) like `SetScreenBacklight [+|-]<value>[%]`, where value can be a brightness value (e.g. 1000) or a percentage (e.g. 0.5 or 50%) of its maximum, either absolute or relative to the actual brightness.

For example, `SetScreenBacklight +10%` would raise the brightness by 10%, while `SetScreenBacklight 0.5` would set its brightness to half its maximum.

Same goes for an eventual `SetKeyboardBacklight` method (see #44).

(Do not mind the method names too much as they are yet to be defined.)

This would work like a charm with:

* clight's auto-calibration [turned off](3acda50);
* *systemd-backlight* which job is just to remember the brightness value of a given backlight device and restore it on next boot;
* Custom `XF86MonBrightnessDown` and `XF86MonBrightnessUp` key bindings;
* even machines without webcam.

**Comment by FedeDP** [comment]
Moved to Clightd.

**Comment by FedeDP** [comment]
I'd personally add a new exposed method to Clightd/Backlight module: SetIncrement: for positive integers it will take current backlight level and increase it of X%; for negative integers it will decrease it.
I think this should expose smooth interface too.

**Comment by vivien** [comment]
> I think you are confusing Clight and Clightd :) (and that is quite normal as I chose a very poor naming!)

Oops sorry, I just opened an issue without asking myself which component would be responsible for this implementation first. For the naming I would have suggested the **ambient** project (think ambient light, ambient brightness and ambient temperature) with classic *ambientd* and *ambientctl* components!
(all of them in the same repository would help as well IMHO.)

> As Clightd only supports percentage values (it was a design choice, as /sys/class/backlight interfaces always have very broad and different max_brightness values), i'd only add support for pct increase/decrease.

It totally make sense. *raw* type backlight drivers can be above 1500, while *firmware* type backlight are up to 15. The interface will be more consistent with percentage only values.

> Again, I think this can be a nice occasion for you to dive into Clightd code, if you are willing to.

I plan to contribute to the project, however it's tight at the moment.

> I'd personally add a new exposed method to Clightd/Backlight module: SetIncrement: for positive integers it will take current backlight level and increase it of X%; for negative integers it will decrease it.

It's weird to have a negative "increment", while this already has a name: "decrement" ;-)
Two methods `RaiseBrightness` and `LowerBrightness` can be considered, even though `SetBrightness` is quite explicit.

**Comment by FedeDP** [comment]
> Oops sorry, I just opened an issue without asking myself which component would be responsible for this implementation first. For the naming I would have suggested the ambient project (think ambient light, ambient brightness and ambient temperature) with classic ambientd and ambientctl components!
(all of them in the same repository would help as well IMHO.)

Yeah..but I loved the "C Light" pun :)

> It's weird to have a negative "increment", while this already has a name: "decrement" ;-)
Two methods RaiseBrightness and LowerBrightness can be considered, even though SetBrightness is quite explicit.

Yes i think that is ok. They will probably be `/org/clightd/clightd/Backlight Raise/Lower "i"`.

**Comment by vivien** [comment]
Ouch I didn’t realize what « C light » was, Wikipedia taught me and now it
makes all sense to me! Pretty great name actually!

**Comment by FedeDP** [comment]
> Ouch I didn’t realize what « C light » was, Wikipedia taught me and now it makes all sense to me! Pretty great name actually!

That, plus "See Light" pronunciation :)

**Comment by vivien** [comment]
And C being the language of choice obviously :mindblown:

**Comment by FedeDP** [comment]
Raise/Lower have been implemented! Have a look here: https://github.com/FedeDP/Clightd/wiki/Api#orgclightdclightdbacklight.

Note that even raise/lower can be smoothed. Moreover, i chose to use a double instead of int (ie: 0.05 instead of 5%) to be coherent with "Set" method.

Let me know if you see any issue!
