### ISSUE TITLE
How to enable gamma, idle, etc

### ISSUE THREAD

**Issue by dylanparry** [FedeDP/Clightd#23]
I've managed to get this compiled, and have also compiled `clight` with no issues. They work just fine too. The problem I'm having is that `clightd` has compiled without support for gamme, dpms, idle, ddc, etc, and I can't figure out how to enable them.

I've installed the necessary optional dependencies (headers for xrandr, x11, ddcutil) for gamma, idle, and dcc support, but running `CMAKE` gives me the following showing that these modules aren't enabled:

```
dylanparry:~/Downloads/clightd/build$  cmake ../
-- The C compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'libudev;libmodule>=3.1.0;polkit-gobject-1'
--   Found libudev, version 239
--   Found libmodule, version 3.2.0
--   Found polkit-gobject-1, version 0.105
-- Checking for one of the modules 'libelogind;libsystemd>=221'
-- GAMMA support disabled
-- DPMS support disabled
-- IDLE support disabled
-- DDC support disabled
-- Checking for module 'libsystemd'
--   Found libsystemd, version 239
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dylanparry/Downloads/clightd/build
```

Any ideas?

**Comment by FedeDP** [comment]
Hi again! Thanks for opening this issue!
It seems i've been quite too lazy lately :) (you know, xmas time etc etc).
I forgot to update wiki pages with latest release. You need to issue a
```
 cmake \
        -G "Unix Makefiles" \
        -DCMAKE_BUILD_TYPE="Release" \
        -DENABLE_DDC=1 -DENABLE_GAMMA=1 -DENABLE_IDLE=1 -DENABLE_DPMS=1 \
        ..
```
As these options must now be explicitly enabled.
I will update wiki pages asap.
Thank you very much for your patience!

EDIT: wiki page is now updated: https://github.com/FedeDP/Clightd/wiki/Build.

**Comment by dylanparry** [comment]
Perfect, thanks for the quick response :)
