### ISSUE TITLE
Camera ambient brightness avg versus max

### ISSUE THREAD

**Issue by pdf** [FedeDP/Clightd#25]
I see that the current method for calculating ambient brightness takes an average of brightness over all pixels in a sample, but I wonder if it wouldn't be a better idea to take the max, or perhaps quantize and use the 99th percentile to avoid outliers (or use wider buckets and take the second-to-last bucket, for less variability).

The problem I'm seeing with using the average is that a dark background (eg dark wallpaper or furniture) can significantly lower avg brightness measurements, and it's not possible to work around this using brightness curves, because the problem is environment-/location-specific (ie - based on background, one location may read as significantly brighter than another, at the same real ambient light level).

**Comment by FedeDP** [comment]
This surely is a neat idea!
I think this is the better approach:
>  quantize and use the 99th percentile to avoid outliers

Are you willing to work on this by chance? It would be greatly appreciated!
I'd like to have this one in next release, if possible!

I'm currently reworking DPMS to have it working on tty too, then Clight/Clightd will enter freezing phase where i just wait a couple of weeks and fix bugs when reported. Then I finally hope to release new version for both!

**Comment by pdf** [comment]
Might need to think a little more about what the correct approach is. My concern with just taking the max value (which is clearly very simple, and might actually be good enough?) is that noisy sensors might produce values that are far from reality, but I'm not sure how likely that actually is.  _If_ this is possible, then I'd guess it's also possible that a very noisy sensor could produce a lot of these pixels, which would make them difficult to filter out using stats.

My current thinking is just to drop maybe the top couple of percent (of relative brightness between min and max) of samples and return the next highest result, but I'm not really sure if this is necessary, or particularly useful to be honest - this is not really a problem-space I'm familiar with.

**Comment by FedeDP** [comment]
We can use an histogram of grayscale values (between 0 and 255) and only keep around top 90% (to remove possibly wrong information), then compute average on these values.
What do you think?

**Comment by pdf** [comment]
We just want the Y component, which is 8-bit already, right? We can find the min/max during stream capture and create a histogram for that range with a fixed number of steps (`max - min / steps = bucket_width`), then average the top bucket. By adjusting the number of steps you can increase or decrease the sample size for the avg.

I think it's probably worth trying this out with a 10-20% sample, to see what the results are like.  We don't need the full histogram either, so we can probably just track the sum and count for the upper bucket, by filtering the samples on `brightness > ((max - min) / steps * (steps-1))`.

**Comment by FedeDP** [comment]
> We just want the Y component, which is 8-bit already, right? 

Yes!

> We can find the min/max during stream capture

Can we? I don't really think so! 

I think we must parse our buffer once to fill our histogram (eventually splitting it in "buckets" (eg: 0-20, 21-40, 41-60 etc etc until 255), and then cycle between 0 and 255 with a step of "bucket_size", to find bucket with most "volume".

It would be great if you could try this out, with different bucket sizes too! :)

**Comment by pdf** [comment]
I haven't written any C in a long time but I can take a shot at it, should be moderately straight-forward I think.

**Comment by pdf** [comment]
> Can we? I don't really think so!

This became clear as I looked a little more closely at how the capture works. I've posted an initial PR for you to review, at your leisure.
