### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by JuergenBausa** [FedeDP/Clightd#28]
I am trying to build clightd on debian buster. However, cmake gives me the following error message:

`jba@lina:/usr/src/Clightd-master/build$ cmake     -G "Unix Makefiles"     -DCMAKE_INSTALL_PREFIX=/usr     -DCMAKE_INSTALL_LIBDIR=lib     -DCMAKE_BUILD_TYPE="Release"     -DENABLE_DDC=1 -DENABLE_GAMMA=1 -DENABLE_DPMS=1 -DENABLE_SCREEN=1     ..
-- Checking for modules 'libudev;libmodule>=4.0.0'
--   No package 'libmodule' found
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  CMakeLists.txt:27 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/usr/src/Clightd-master/build/CMakeFiles/CMakeOutput.log".
`

What package do I need to install?

In the original post (two years ago) it was said, that "In each repository you can find deb files inside Debian folder.". Didnt find them. Would be much easier for debian users, if the debs would be there.

Juergen

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue.

Libmodule is an external dependency. Have a look at wiki pages for more detailed explanation about how to build: https://github.com/FedeDP/Clightd/wiki/Build.
Note that wiki pages always refer to -git versions, thus some instructions may be little different.

> In the original post (two years ago) it was said, that "In each repository you can find deb files inside Debian folder."

Yes; unfortunately this behaviour was changed as i always have less and less time to spend on my side projects (and always more and more side projects/ideas too!); thus i hadn't really time to spend on continuously fixing any packaging issue too.

**Comment by JuergenBausa** [comment]
Thanks for the fast answer. and sorry for not reading the instructions carefully.

But now I have another problem. I installed ddcutil 0.9.2-1 which is in debian buster.

However, configure asks for 9.5 or higher. I tried to install a more recent ddcutil from source, but this didnt work in configure. I think the reason is, that debians autoconf tools are outdated.

Is there any way to build clightd using ddcutil 0.9.2-1?

Juergen

**Comment by FedeDP** [comment]
> Is there any way to build clightd using ddcutil 0.9.2-1?

Unfortunately i always stick with latest ddcutil version available as it is an evolving API with lots of fixes each release.
Moreover, Debian (and ubuntu) do not even package ddcutil library; they only package ddcutil binary program.
Thus you'll have to build from git.

> However, configure asks for 9.5 or higher. I tried to install a more recent ddcutil from source, but this didnt work in configure. I think the reason is, that debians autoconf tools are outdated.

This is weird; is this not working for you?
```
cd ddcutil
./autogen.sh
./configure --prefix=/usr
make
sudo make install
```

**Comment by JuergenBausa** [comment]
I found out, that I was missing libtool. After installation of libtool, I could compile and install 
ddcutil from source.

I was then able to build the deb for clightd. However, Installation fails, because it depends on 
ddcutil >=0.9.5. This is now installed, but not as a deb package.

Is there a way to remove this dependency from clightd? Maybe just by changing 
CMakeLists.txt?

Jürgen




Am Montag, 26. August 2019, 10:15:12 CEST schrieb Federico:
> > Is there any way to build clightd using ddcutil 0.9.2-1?
> 
> Unfortunately i always stick with latest ddcutil version available as it is
> an evolving API with lots of fixes each release. Moreover, Debian (and
> ubuntu) do not even package ddcutil library; they only package ddcutil
> binary program. Thus you'll have to build from git.
> 
> > However, configure asks for 9.5 or higher. I tried to install a more
> > recent ddcutil from source, but this didnt work in configure. I think the
> > reason is, that debians autoconf tools are outdated.
> This is weird; is this not working for you?
> ```
> cd ddcutil
> ./autogen.sh
> ./configure --prefix=/usr
> make
> sudo make install
> ```

**Comment by FedeDP** [comment]
> I found out, that I was missing libtool. After installation of libtool, I could compile and install
ddcutil from source.

Great!

> Is there a way to remove this dependency from clightd? Maybe just by changing
CMakeLists.txt?

Yes, just comment out L173-174 of CMakeLists.txt: https://github.com/FedeDP/Clightd/blob/master/CMakeLists.txt#L173

**Comment by JuergenBausa** [comment]
> > Is there a way to remove this dependency from clightd? Maybe just by
> > changing
> CMakeLists.txt?
> 
> Yes, just comment out L173-174 of CMakeLists.txt:
> https://github.com/FedeDP/Clightd/blob/master/CMakeLists.txt#L173

That worked. Thanks!

Jürgen

**Comment by FedeDP** [comment]
Great!
