### ISSUE TITLE
Dependency "polkitd.service" in ubuntu 16.04 not automatically set for me through clightd cmake

### ISSUE THREAD

**Issue by ModDM** [FedeDP/Clightd#30]
Clight does not start and shows this error:
`Error loading from cache file.`

Any idea what this means?

Another user advised me to restart Clightd, so I did, and perhaps that shows the underlying problem:

```
~$ systemctl restart clightd
Failed to restart clightd.service: Unit polkit.service not found.
```

Additional comments I received about this in issue 98 is:
Quote from FedeDP:

> This is weird; polkit systemd unit is called "polkitd.service" in ubuntu 16.04 (there is even a comment in Clightd CMakeLists.txt: https://github.com/FedeDP/Clightd/blob/master/CMakeLists.txt#L104).
> The dependency should be automatically set for you through clightd cmake. If that's not the case, please open an issue on Clightd!

Hope to see a solution soon, so that my Clight can start again! (issue started after installation of the newest Clight files from master with your latest work in it).

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue.
As a quick workaround, you can manually fix your clightd.service, setting:
`Requires=polkitd.service`  instead of "polkit.service" (note the additional 'd').

You should find clightd.service installed in `/usr/lib/systemd/system/clightd.service`.

**Comment by FedeDP** [comment]
The error is on this line: https://github.com/FedeDP/Clightd/blob/master/CMakeLists.txt#L105. I will fix it asap!

**Comment by FedeDP** [comment]
Can you test by changing clightd CMakeLists Line 105 from
`find_file(POLKITD lib/systemd/system/polkitd.service)`
to
`find_file(POLKITD /lib/systemd/system/polkitd.service)`
? 
Then run again cmake for Clightd and make and make install!
After that, check that /usr/lib/systemd/system/clightd.service now has "polkitd.service".
Thanks!

**Comment by ModDM** [comment]
On all places I made sure polkitd is set and not polkit. After installation of Clightd I also will check that this is the case. However, I can not install Clightd because it says Ddcutil is not installed. So, I did that again with no error. But, still Clightd does not see Ddcutil. This is what I did:

```
sysuser:~/Downloads/Clightd$ mkdir build
sysuser:~/Downloads/Clightd$ cd build
sysuser:~/Downloads/Clightd/build$ cmake \
>     -G "Unix Makefiles" \
>     -DCMAKE_INSTALL_PREFIX=/usr \
>     -DCMAKE_INSTALL_LIBDIR=lib \
>     -DCMAKE_BUILD_TYPE="Release" \
>     -DENABLE_DDC=1 -DENABLE_GAMMA=1 -DENABLE_DPMS=1 -DENABLE_SCREEN=1 \
>     ..
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'libudev;libmodule>=4.0.0'
--   Found libudev, version 229
--   Found libmodule, version 5.0.0
-- Checking for module 'polkit-gobject-1'
--   Found polkit-gobject-1, version 0.105
-- Checking for one of the modules 'libelogind;libsystemd>=221'
-- Checking for modules 'x11;xrandr'
--   Found x11, version 1.6.3
--   Found xrandr, version 1.5.0
-- GAMMA support enabled
-- Checking for modules 'x11;xext'
--   Found x11, version 1.6.3
--   Found xext, version 1.3.3
-- DPMS support enabled
-- Checking for module 'x11'
--   Found x11, version 1.6.3
-- SCREEN support enabled
-- Checking for module 'ddcutil>=0.9.5'
--   Found ddcutil, version 0.9.5
-- DDC support enabled
-- Checking for module 'libsystemd'
--   Found libsystemd, version 229
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sysuser/Downloads/Clightd/build
sysuser:~/Downloads/Clightd/build$ make
Scanning dependencies of target clightd
[  6%] Building C object CMakeFiles/clightd.dir/src/main.c.o
[ 12%] Building C object CMakeFiles/clightd.dir/src/utils/udev.c.o
[ 18%] Building C object CMakeFiles/clightd.dir/src/utils/polkit.c.o
[ 25%] Building C object CMakeFiles/clightd.dir/src/modules/dpms.c.o
[ 31%] Building C object CMakeFiles/clightd.dir/src/modules/gamma.c.o
/home/sysuser/Downloads/Clightd/src/modules/gamma.c: In function ‘receive’:
/home/sysuser/Downloads/Clightd/src/modules/gamma.c:76:9: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
         read(smooth_fd, &t, sizeof(uint64_t));
         ^
[ 37%] Building C object CMakeFiles/clightd.dir/src/modules/sensors/camera.c.o
[ 43%] Building C object CMakeFiles/clightd.dir/src/modules/sensors/als.c.o
[ 50%] Building C object CMakeFiles/clightd.dir/src/modules/sensor.c.o
[ 56%] Building C object CMakeFiles/clightd.dir/src/modules/backlight.c.o
/home/sysuser/Downloads/Clightd/src/modules/backlight.c: In function ‘receive’:
/home/sysuser/Downloads/Clightd/src/modules/backlight.c:190:9: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
         read(sc->smooth_fd, &t, sizeof(uint64_t));
         ^
[ 62%] Building C object CMakeFiles/clightd.dir/src/modules/signal.c.o
[ 68%] Building C object CMakeFiles/clightd.dir/src/modules/bus.c.o
[ 75%] Building C object CMakeFiles/clightd.dir/src/modules/idle.c.o
/home/sysuser/Downloads/Clightd/src/modules/idle.c: In function ‘receive’:
/home/sysuser/Downloads/Clightd/src/modules/idle.c:112:17: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
                 read(msg->fd_msg->fd, &t, sizeof(uint64_t));
                 ^
[ 81%] Building C object CMakeFiles/clightd.dir/src/modules/dpms_plugins/xorg.c.o
[ 87%] Building C object CMakeFiles/clightd.dir/src/modules/dpms_plugins/tty.c.o
[ 93%] Building C object CMakeFiles/clightd.dir/src/modules/screen.c.o
[100%] Linking C executable clightd
[100%] Built target clightd
sysuser:~/Downloads/Clightd/build$ cpack -G DEB
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: clightd
CPack: - Install project: clightd
CPack: Create package
CPack: - package: /home/sysuser/Downloads/Clightd/build/clightd-4.0-Linux.deb generated.
sysuser:~/Downloads/Clightd/build$ sudo dpkg -i clightd-4.0-Linux.deb
(Reading database ... 345415 files and directories currently installed.)
Preparing to unpack clightd-4.0-Linux.deb ...
Unpacking clightd (4.0) over (4.0) ...
dpkg: dependency problems prevent configuration of clightd:
 clightd depends on ddcutil (>= 0.9.5); however:
  Package ddcutil is not installed.

dpkg: error processing package clightd (--install):
 dependency problems - leaving unconfigured
Processing triggers for dbus (1.10.6-1ubuntu3.4) ...
Errors were encountered while processing:
 clightd

```

**Comment by ModDM** [comment]
And this is how I installed Ddcutil:

```
./autogen.sh
./configure --prefix=/usr --enable-lib
make
sudo make install
```

**Comment by FedeDP** [comment]
> dpkg: dependency problems prevent configuration of clightd:
 clightd depends on ddcutil (>= 0.9.5); however:
  Package ddcutil is not installed.

Dpkg tries to find a ddcutil package as dependency. Unfortunately ddcutil API is not packaged in ubuntu. Thus, it says it fails to find a ddcutil package and consequently it warns you that a dependency is missing, even if library is indeed installed (manually!).
You can drop 'ddcutil' from dependencies in CMakeLists.txt  by removing [line 173](https://github.com/FedeDP/Clightd/blob/master/CMakeLists.txt#L173).

**Comment by ModDM** [comment]
I have literally done everything, I:
- changed polkit to poliktd in `/usr/lib/systemd/system/clightd.service`
( `Requires=polkitd.service` instead of "`polkit.service`" (note the additional 'd') )
- changed `find_file(POLKITD lib/systemd/system/polkitd.service)`
to
`find_file(POLKITD /lib/systemd/system/polkitd.service)` (only added a slash before it)
, reinstalled ddcutil, reinstalled Clightd, reinstalled Clight, checked all files again and made sure the changes are done, but when I now try this:
`systemctl restart clightd`
it shows the error:
`Failed to restart clightd.service: Unit polkit.service not found.`
Clight is still not working (not able to start due to the startup error `Error loading from cache file.`.

**Comment by FedeDP** [comment]
>  Failed to restart clightd.service: Unit polkit.service not found.

Clightd is still looking for polkit.service instead of polkitd.service. Can you manually change /usr/lib/systemd/system/clightd.service again? Then issue a 
`sudo systemctl daemon-reload`
and try to restart clightd!

**Comment by ModDM** [comment]
`Can you manually change /usr/lib/systemd/system/clightd.service again?`
It is changed. I made sure. That's why I post this issue, I have done everything.
But, good news: `sudo systemctl daemon-reload` did the trick regarding polkit(d).
When I now do this:
`systemctl restart clightd`, it just works, not any error anymore. I think I will now go back to the Clight issue and post there that the startup error is still present? (`Error loading from cache file..`).

**Comment by FedeDP** [comment]
Great!
> Error loading from cache file..

This is not an error, it means it could not load a cached location from a previous clight cache.

**Comment by ModDM** [comment]
Ok, but normally you see Clight starting up with the right gamma settings, brightness settings etc., but now the terminal does not show that, it seems the process does not go further after this error?

**Comment by FedeDP** [comment]
Mmh if it cannot find any cached location and geoclue2 does not give any location, gamma module hangs (ie: waits for geoclue).
Moreover, backlight waits on gamma module to know which daytime we are in (DAY or NIGHT), thus it hangs too.

If this happens again, give it some time (eg 1min). If geoclue2 is still not giving any location, try to set a fixed location in clight conf file.

**Comment by ModDM** [comment]
You mean longitute and latitude?

I have set that. Strange. Clight deos not show brightness or gamma values at startup. This is my terminal screen now for some minutes:
```
clight
Config file /home/sysuser/.config/clight.conf not found.
Clightd found, version: 4.0.
Initial AC state: connected.
Failed to create org.freedesktop.ScreenSaver dbus interface: Unknown error -1
Next alarm due to: Mon Sep  9 19:21:00 2019
Keyboard backlight calibration unsupported.
```

**Comment by ModDM** [comment]
But as you can see, the line starting with the word 'error' is gone.

**Comment by ModDM** [comment]
And when I let Clight run, something my screen totally turns off and I can't get it on again. Then I only can lock the screen and with still no screen I have to run any FN function of my laptop (eg. sound FN key) and then my screen is back again. This is no modest dim, but dramatically turning off the screen.

**Comment by ModDM** [comment]
Clight ambient gamma is not working. I tested it even with a delay of 2 seconds to quickly see if it changes when I hold something in front of the webcam (blocking the light), but it does not work.

**Comment by ModDM** [comment]
terminal also not showing any brightness or gamma levels, even after many minutes.

**Comment by FedeDP** [comment]
> But as you can see, the line starting with the word 'error' is gone.

Yes, it does not try to find a cached location if a fixed location is set.

> And when I let Clight run, something my screen totally turns off and I can't get it on again.

DPMS kicking in!

This is super weird though, i don't understand what's happening :(
What does 
`busctl call org.clightd.clightd /org/clightd/clightd/Sensor org.clightd.clightd.Sensor Capture "sis" "" 5 ""`
print?

**Comment by ModDM** [comment]
```
~$ busctl call org.clightd.clightd /org/clightd/clightd/Sensor org.clightd.clightd.Sensor Capture "sis" "" 5 ""
Invalid arguments 'sis' to call org.clightd.clightd.Sensor.Capture(), expecting 'si'.

```

**Comment by FedeDP** [comment]
It seems you are not using latest clightd! "sis" is current Capture method signature in master.

**Comment by ModDM** [comment]
Oh, you nice guy! You said I only needed to download and install newest Clight from master and newest Libmodule (in the "More points in curve" Clight issue 95). But now I see there is also a newer Clightd needed. In fact very good that the software is always updated. Let me test this again. Any more outdated things? Ddcutil also outdated? I can also download that again, if needed.

**Comment by ModDM** [comment]
Good to know there is a clue. I gladly install the newest one! One problem: Before I installed the newest Clightd I had version 4 (if I am not mistaken) and after I installed it yet, I still seem to have version 4. When Clight starts it shows this:

```
clight
Config file /home/sysuser/.config/clight.conf not found.
Clightd found, version: 4.0.
Initial AC state: connected.
Failed to create org.freedesktop.ScreenSaver dbus interface: Unknown error -1
Next alarm due to: Mon Sep  9 19:21:00 2019
Keyboard backlight calibration unsupported.

```

**Comment by ModDM** [comment]
I still have no brightness or gamma levels showing in the terminal / log.

**Comment by ModDM** [comment]
And I still have this:

```
~$ busctl call org.clightd.clightd /org/clightd/clightd/Sensor org.clightd.clightd.Sensor Capture "sis" "" 5 ""
Invalid arguments 'sis' to call org.clightd.clightd.Sensor.Capture(), expecting 'si'.
```

**Comment by ModDM** [comment]
Yes whoopie! Works, restarted my PC, All working! Thanks mister FedeDP for your wonderful help all time!

**Comment by FedeDP** [comment]
GREAAAAAT! 

I am sorry i broke clight for a couple of days for you :(
