### ISSUE TITLE
Gamma Temp feels not correct

### ISSUE THREAD

**Issue by mindrunner** [FedeDP/Clightd#36]
Every day at 6pm (sunset) my screen is supposed to go to nicht mode. I can see this in the log:
```
(I)[18:07:00]{gamma.c:330}	Normal transition to 4500 gamma temp started.
```
So far, so good. 

However, my impression sometimes is, that the temp did not fully go where it is supposed to be. If I enforce a transition to `6500` (e.g. by starting caffeine or a youtube video) and then letting it go to night mode again, it feels way less blueish than before. I know, this might be an optical illusion, but I am pretty sure it is not. But it i also really hard to tell....

Is there anything else I could use to prove on which temp settings I am than my unreliable eyes?

**Comment by FedeDP** [comment]
You can check screen temperature with
`busctl call org.clightd.clightd /org/clightd/clightd/Gamma org.clightd.clightd.Gamma Get "ss" ":0" "$HOME/.Xauthority"`

It may be just a feeling though :)

**Comment by mindrunner** [comment]
Where exactly does this value come from? Is that what clight thinks the setting is (feeling)? Or does the system return the current gamma somehow?

**Comment by FedeDP** [comment]
Clightd does not store last setted temp, thus when you call "Get" method, it calls a [get_gamma](https://github.com/FedeDP/Clightd/blob/master/src/modules/gamma.c#L322) function, that, as you can see, calls Xlib functions to retrieve current gamma temperature; so, unless [get_temp](https://github.com/FedeDP/Clightd/blob/master/src/modules/gamma.c#L258) is terribly wrong, that should be current screen temperature value as read for X.

I do not know if there are any external program to actually validate that value; i am pretty sure there are multiple ones though!

**Comment by mindrunner** [comment]
> I do not know if there are any external program to actually validate that value; i am pretty sure there are multiple ones though!

I remember trying to find one in the past, because I used to have other problems with that. Could not find any reliable one. Will monitor this and probably report back.

Thanks for helping! :)

**Comment by FedeDP** [comment]
Thanks for testing! :smiley:

**Comment by mindrunner** [comment]
I think, everything is alright and it's just my eyes being a problem sometimes. Cheers! :)
