### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by finkrer** [FedeDP/Clightd#40]
Clight seems to occasionally go in a state where it uses a lot of CPU. It sits at 12% for me until I kill the process. This is someting that has been occurring for a few months.

I use the latest stable version from the AUR on Arch Linux.

![image](https://user-images.githubusercontent.com/22712590/83743529-460e9780-a674-11ea-8e3c-28f8df3170c9.png)

**Comment by FedeDP** [comment]
Hi! Thanks for opening the issue...but this is the wrong repo :)
You should use https://github.com/FedeDP/Clight for Clight!
Anyway, the bug is already tracked there: https://github.com/FedeDP/Clight/issues/106. 
Can you share some more info on that issue?
