### ISSUE TITLE
cannot disable clight(d)

### ISSUE THREAD

**Issue by mindrunner** [FedeDP/Clightd#42]
I am in arch linux. Even when disabling the clightd.service unit, after a while clight and clightd are running again. Cannot figure out why. Any idea why this might happen?

Cheers
Lukas

```
● clightd.service - Bus service to manage various screen related properties (gamma, dpms, backlight)
     Loaded: loaded (/usr/lib/systemd/system/clightd.service; disabled; vendor preset: disabled)
     Active: active (running) since Mon 2020-06-29 11:59:30 CEST; 1h 2min ago
   Main PID: 155514 (clightd)
      Tasks: 2 (limit: 38352)
     Memory: 2.6M
     CGroup: /system.slice/clightd.service
             └─155514 /usr/lib/clightd/clightd
```

**Comment by FedeDP** [comment]
Hi @mindrunner !
You can disable Clightd unit, but it will be kicked in as a dependency by Clight during its startup.
You must disable Clight from autostart too.

**Comment by mindrunner** [comment]
I killed clight as well, still clight as well as clightd was restarted automatically. :(

**Comment by FedeDP** [comment]
Did you stop clightd after killing clight?
There is no autorestart behavior in clight btw... Try to check your DE autostarting application settings!

**Comment by mindrunner** [comment]
I will try to reproduce it again.

**Comment by mindrunner** [comment]
Seems like you're right. :)
How is clight (run as a user) able to start a system service? Don't you need root permission for this?

**Comment by FedeDP** [comment]
Have a look at https://dbus.freedesktop.org/doc/system-activation.txt and corrispective clightd activation script: https://github.com/FedeDP/Clightd/blob/master/Scripts/org.clightd.clightd.service :)

This way, when clight calls a  clightd method for the first time, if clightd is not started yet, it will get started.

The  same goes for [clight](https://github.com/FedeDP/Clight/blob/master/Extra/org.clight.clight.service); if you try to do a quick calibrate while clight is not running, clight will get started!

**Comment by mindrunner** [comment]
Cool, thanks for the explanation! :)

**Comment by FedeDP** [comment]
You are welcome :)
