### ISSUE TITLE
Deb cpack dependecy missing on Debian and control file issue

### ISSUE THREAD

**Issue by NICHOLAS85** [FedeDP/Clightd#45]
The newly added libjpeg-turbo8 dependency does not exist on Debian repos. I believe it's equivalent is libjpeg62-turbo.

There also seems to be a missing comma here https://github.com/FedeDP/Clightd/blob/90d2444de3520953fe96bc1a3126db9340cd85a6/CMakeLists.txt#L169
after `libsystemd0` which is creating a broken deb

**Comment by FedeDP** [comment]
Hi! Thanks for pointing it out :) should be fixed in latest master!

**Comment by NICHOLAS85** [comment]
Package works correctly now! However, it seems you also changed the ddcutil dependency to libddcutil which broke things again as that package doesn't exist on Debian :(. Are they planning on renaming the package in the future or is that an Ubuntu specific thing

**Comment by FedeDP** [comment]
Ops! Should be fixed now!

**Comment by FedeDP** [comment]
@NICHOLAS85 Any news on this?

**Comment by NICHOLAS85** [comment]
Looks like it's packing correctly for me now!
