### ISSUE TITLE
Error when using make

### ISSUE THREAD

**Issue by sexpistols77** [FedeDP/Clightd#48]
Hi, I am trying to install Clightd by following the build instructions on the wiki, but for some reason when it comes to executing the make command on the /Clightd/build/ folder, I get these errors:

>[  3%] Linking C executable clightd
/usr/bin/ld: CMakeFiles/clightd.dir/src/modules/gamma_plugins/drm.c.o: in function `set':
drm.c:(.text+0x16a): undefined reference to `drmIsMaster'
/usr/bin/ld: CMakeFiles/clightd.dir/src/modules/dpms_plugins/drm.c.o: in function `set':
drm.c:(.text+0x27): undefined reference to `drmIsMaster'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/clightd.dir/build.make:460: clightd] Fel 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/clightd.dir/all] Fel 2
make: *** [Makefile:152: all] Fel 2

_Note: "Fel" means error in Swedish._

Any idea om what this is and how can I fix it? Thanks in advance! :)

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue!
It seems like you are missing libdrm! On which distro are you?
Note: i forgot to update list of deps in [Getting started](https://github.com/FedeDP/Clightd/wiki/Getting-Started) page...

**Comment by sexpistols77** [comment]
I'm on Debian 10! I already have libdrm-dev installed, which I thought was the correct one?

**Comment by FedeDP** [comment]
Oh i found out that `drmIsMaster` api was only available since libdrm 2.4.98 (not present on debian buster).
I dropped the use of that api as it was unnecessary anyway. It should fix your build!

**Comment by sexpistols77** [comment]
Thank you! That fixed the issue! :)
