### ISSUE TITLE
problem setting brightness (relies on udev)

### ISSUE THREAD

**Issue by nick87720z** [FedeDP/Clightd#5]
When calling setallbrightness with arguments 0.6, (0,0,0), <path to acpi backlight ctl dir>,
it fails due to permission with ubuntu 16.04.

**Comment by FedeDP** [comment]
Can you try to issue:
`$ busctl call org.clightd.backlight /org/clightd/backlight org.clightd.backlight setallbrightness "d(bdu)s" 0.7 0 0 0 ""`

Btw are you using clight on desktop pc or laptop?

EDIT: Note that you only need last part of syspath (eg: "intel_backlight"), and that an empty path will let clightd default to first backlight device it finds.

**Comment by nick87720z** [comment]
Hm, yes, with empty string or "intel_backlight" it works.

**Comment by nick87720z** [comment]
Again seems to be clight client issue :)

**Comment by FedeDP** [comment]
As explicitly stated in clight conf file: https://github.com/FedeDP/Clight/blob/master/Extra/clight.conf#L114:

> Screen syspath to be used (only last part of syspath)
> screen_sysname = "intel_backlight";  

I guess you instead setted "/sys/class/backlight/intel_backlight" there :)

EDIT: btw you can leave it commented too, as i already said (and as clight is a 0-conf software) it will use first backlight subsystem device it finds.

**Comment by nick87720z** [comment]
It is on laptop.

**Comment by nick87720z** [comment]
I uncommented screen_sysname line, but it still says about bad permissions.

**Comment by FedeDP** [comment]
Can you paste here your conf file?

**Comment by nick87720z** [comment]
Problem seems to be in bus.c: call() code again. During setallbrightness it does only two iterations (second is not completed), then ends with permission error.

**Comment by FedeDP** [comment]
I see (sorry but obviously i could not test the patch i sent you, because i have systemd >= 234).  
So we can move back to your issue on clight :D

**Comment by nick87720z** [comment]
i understand :)
