### ISSUE TITLE
Wiki Build instructions should refer to virtual packages

### ISSUE THREAD

**Issue by Code7R** [FedeDP/Clightd#50]
Hi,

TLDR: please clone https://github.com/Code7R/Clightd.wiki.git (or add as remote in yours) and merge/cherry-pick latest.

The instructions don't work on latest Debian because some of the dev packages have different names. However, they all provide virtual dependency, thus the modified command line.

> $ sudo apt install build-essential pkg-config cmake libsystemd-dev libxrandr-dev libxext-dev policykit-1 libpolkit-gobject-1-dev libjpeg-dev libusb-dev libwayland-dev libdrm-dev

**Comment by Code7R** [comment]
Another one:

commit 7c1e589955ee7fa423fae51d72debc7a644fd3c9 (HEAD -> master, wiki/master)
Author: Eduard Bloch <blade@debian.org>
Date:   Sat Nov 28 14:06:42 2020 +0100

    Also libddcutil-dev was missing

**Comment by FedeDP** [comment]
Hi! Thank you! Merged it!
