### ISSUE TITLE
Unable to configure file-based input source

### ISSUE THREAD

**Issue by Code7R** [FedeDP/Clightd#51]
Repro steps:

installed clightd and clight following wiki instructions.
Created a text file /etc/clightd/sensors.d/sysname which is owned by a user and is readable to root.
Restarted clightd service.
Used clight.conf from Extra folder in clight for ~/.config/clight.conf .
Started clight.

SCREEN forcefully disabled as Clightd was built without screen support.
Clightd found, version: 5.0.
AC curve: y = -0.024825 + 0.191641x + -0.008928x^2
BATT curve: y = -0.010629 + 0.153844x + -0.007284x^2
init_kbd_backlight(): Keine derartige Schnittstelle »org.freedesktop.UPower.KbdBacklight« des Objekts im Pfad /org/freedesktop/UPower/KbdBacklight
Keyboard backlight calibration unsupported.
Not a laptop device. Killing UPower module.
Failed to retrieve AC state; fallback to ON_AC and OPEN lid.
Emitting AcState property
Emitting LidState property
Error loading from cache file.

Actions

Writing a text value light "20" or "50" into /etc/clightd/sensors.d/sysname has no effect.
Verbosity output also not reporting that /etc/clightd/sensors.d/sysname is used.
Double-checked https://github.com/FedeDP/Clightd/wiki/Sensors assuming that I forgot something. The description is vague, I assume that "sysname" is a bare path name, although putting this into quotes might mean something... but that thing is hard to grasp from the comments in clight.conf sample or wiki.

Double checking inotify:
$sudo ls -la /proc/$(pidof clightd)/fd | grep notify
...
lr-x------ 1 root root 64 28. Nov 14:46 19 -> anon_inode:inotify
lr-x------ 1 root root 64 28. Nov 14:46 31 -> anon_inode:inotify

So it is observing something but what?

**Comment by Code7R** [comment]
Another check:
strace -o log /usr/local/lib/clightd/clightd
Registered 'Als' sensor plugin.
Registered 'Camera' sensor plugin.
Registered 'Custom' sensor plugin.
Registered 'YoctoLight' sensor plugin.
Registered 'Drm' gamma plugin.
Registered 'Wl' gamma plugin.
Registered 'Xorg' gamma plugin.
Registered 'Drm' dpms plugin.
Registered 'Wl' dpms plugin.
Registered 'Xorg' dpms plugin.

I am sure I have built this with DDC enabled but it's not mentioned here.
grep sensors.d log
inotify_add_watch(31, "/etc/clightd/sensors.d/", IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE) = 1

Ok, so I patched it, like

```
diff --git a/src/modules/sensors/custom.c b/src/modules/sensors/custom.c
index 6622ed2..7b9b3dd 100644
--- a/src/modules/sensors/custom.c
+++ b/src/modules/sensors/custom.c
@@ -70,7 +70,7 @@ static void destroy_dev(void *dev) {
 
 static int init_monitor(void) {
     inot_fd = inotify_init();
-    inot_wd = inotify_add_watch(inot_fd, CUSTOM_FLD, IN_CREATE | IN_DELETE | IN_MOVE);
+    inot_wd = inotify_add_watch(inot_fd, CUSTOM_FLD, IN_CREATE | IN_DELETE | IN_MOVE | IN_CLOSE_WRITE);
     return inot_fd;
 }

```

**Now we get at least some activity from strace - but still no proper result.**

> [pid 105459] recvmsg(4,  <unfinished ...>
[pid 105458] epoll_wait(11, [{EPOLLIN, {u32=2695717088, u64=94088249303264}}], 64, -1) = 1
[pid 105458] read(31, "\1\0\0\0\10\0\0\0\0\0\0\0\20\0\0\0sysname\0\0\0\0\0\0\0\0\0", 272) = 32
[pid 105458] access("/etc/clightd/sensors.d/sysname", F_OK) = 0
[pid 105458] sendmsg(10, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1.\0\0\0\7\0\0\0p\0\0\0\1\1o\0\"\0\0\0/org/cli"..., iov_len=128}, {iov_base="\36\0\0\0/etc/clightd/sensors.d/sysna"..., iov_len=46}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 174
[pid 105458] sendmsg(10, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1.\0\0\0\10\0\0\0h\0\0\0\1\1o\0\33\0\0\0/org/cli"..., iov_len=120}, {iov_base="\36\0\0\0/etc/clightd/sensors.d/sysna"..., iov_len=46}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 166

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue!
You can quickly test whether clightd is seeing your Custom sensor by calling:
`busctl call org.clightd.clightd /org/clightd/clightd/Sensor/Custom org.clightd.clightd.Sensor Capture "sis" "" 5 ""`

>  inotify_add_watch(31, "/etc/clightd/sensors.d/", IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE) = 1

Yep, clightd is merely watching the folder to know when a new sensor becomes available.

EDIT: btw can you properly link your full clight.log file? thanks

**Comment by Code7R** [comment]
So I progressed a bit further in the configuration but I can tell you, it is
not straight-forward if your D-Bus know-how is limited and you are not clight
developer. And there is basically no good howto.
Your command is really helpful for a start, maybe such examples should be added to the introduction of the docs.
Otherwise, it becomes really hard to debug the whole chain.

And sorry, your config file is apparently yet another custom made format, and the semantics are not explained there.
So I have to make guesses, like can I configure multiple sections? And each
section is identified by devname= parameter inside? Or something else? Or no
identifier needed?
Also what is "sysname" exactly? I guessed that I can add it as a new parameter
to the config section. (again, guessing that it's ok, should be documented)
I also renamed the input file after it (again, guessing! is this the right way?)

Now it seems to report it as "leo" as reported by busctl (Capture).

I was also assuming that I need to configure the integer range as well but
could not find it in https://github.com/FedeDP/Clightd/wiki/Sensors . However
that page talks about "maximum threshold". I guessed that this was confused
with be **input range maximum** and not some threshold (because otherwise - threshold
for what??).
Now it seems to work when m and M set to match my sensor readings, now I get the
'sad' value scaled properly from 0 to 1.

So far so good. But still no DDCCI activity happening.
So, trying a smoke test on the controller. How? Following https://github.com/FedeDP/Clightd/wiki/Api and trying:

> 
> $ busctl call org.clightd.clightd /org/clightd/clightd/Screen org.clightd.clightd.Screen  GetEmittedBrightness ss $DISPLAY $XAUTHORITY
> Call failed: Unknown method GetEmittedBrightness or interface org.clightd.clightd.Screen.

-> NOPE.

Double-checking clight.conf sample, it says:
# Requires X server and BACKLIGHT. Disabled otherwise. #
What is BACKLIGHT? I checked clightd readme, it was no there. Guessin this is about DDC, I enabled all flags and recompiled, and only THEN Screen interface appeared in dbus.

And only now, after getting there, I see some helpful output from clight.
Maybe it should tell in the beginning that it did not found any screen/backlight to manage if this is the case?
So, finally, here we go, here is the log after a couple of minutes. In the meantime I tried putting low and high values into the input file.
But this seems to make no difference on the screen.

> ± clight 
> Clightd found, version: 5.0.
> AC curve: y = -0.024825 + 0.191641x + -0.008928x^2
> BATT curve: y = -0.010629 + 0.153844x + -0.007284x^2
> init_kbd_backlight(): Keine derartige Schnittstelle »org.freedesktop.UPower.KbdBacklight« des Objekts im Pfad /org/freedesktop/UPower/KbdBacklight
> Keyboard backlight calibration unsupported.
> Not a laptop device. Killing UPower module.
> Failed to retrieve AC state; fallback to ON_AC and OPEN lid.
> Emitting AcState property
> Set timeout of 0s 1ns on fd 40.
> Emitting LidState property
> Set timeout of 30s 0ns on fd 40.
> Error loading from cache file.
> Set timeout of 30s 0ns on fd 40.
> Set timeout of 30s 0ns on fd 40.
> Set timeout of 30s 0ns on fd 40.
> Set timeout of 30s 0ns on fd 40.
> Set timeout of 30s 0ns on fd 40.
> Set timeout of 30s 0ns on fd 40.
> Set timeout of 30s 0ns on fd 40.
> Start compensating for screen-emitted brightness.
> Set timeout of 30s 0ns on fd 40.
> Average screen-emitted brightness: 0.021765.
> Set timeout of 30s 0ns on fd 40.
> Emitting ScreenComp property
> Average screen-emitted brightness: 0.021686.
> Set timeout of 30s 0ns on fd 40.
> Emitting ScreenComp property
> Average screen-emitted brightness: 0.021608.
> Set timeout of 30s 0ns on fd 40.
> Emitting ScreenComp property
> Entering dimmed state...
> A lower than dimmer_pct backlight level is already set. Avoid changing it.
> Emitting DisplayState property
> Leaving dimmed state...
> Emitting DisplayState property
> Average screen-emitted brightness: 0.021608.
> Set timeout of 30s 0ns on fd 40.
> Average screen-emitted brightness: 0.030431.
> Set timeout of 30s 0ns on fd 40.
> Emitting ScreenComp property
> Average screen-emitted brightness: 0.030353.
> Set timeout of 30s 0ns on fd 40.
> Emitting ScreenComp property
> Entering dimmed state...
> A lower than dimmer_pct backlight level is already set. Avoid changing it.
> Emitting DisplayState property
> Leaving dimmed state...
> Emitting DisplayState property
> Average screen-emitted brightness: 0.030314.
> Set timeout of 30s 0ns on fd 40.
> Emitting ScreenComp property
> ^CReceived 2. Leaving.
> 
> 

What's the reason? I have monitored for a while:

> $ watch busctl call org.clightd.clightd /org/clightd/clightd/Screen org.clightd.clightd.Screen  GetEmittedBrightness ss $DISPLAY $XAUTHORITY

The result is changing slowly, between 0.043 and <0.055.
Which is a) much much lower than Sensor/Capture output reports, b) even if that was applied through ddcutil, something should change on the screen, but it doesn't.

Can I set it somehow? There seems to be no SetEmittedBrightness method AFAICS.

Last but not least: 
while I was playing with clight.conf, it seems that the clightd was outputing some messages:

> : Expected a=b format.

This is not helpful if this only goes to hidden output of the daemon. What was the offending keyword?



PS: conf file in current form:
[clight.conf.txt](https://github.com/FedeDP/Clightd/files/5610916/clight.conf.txt)

**Comment by FedeDP** [comment]
> it is not straight-forward if your D-Bus know-how is limited

Sorry but this is a dbus service...

>  Your command is really helpful for a start, maybe such examples should be added to the introduction of the docs.

You are right: it can be useful! Will add them asap!

> And sorry, your config file is apparently yet another custom made format, and the semantics are not explained there.

Guessing you are talking about clight configuration file here.   
It is [libconfig](https://github.com/hyperrealm/libconfig) default format.
I think it is pretty common indeed.

> So I have to make guesses, like can I configure multiple sections? 

Yes, clight conf is splitted into sections for each feature it provides.

> And each section is identified by devname= parameter inside? Or something else? Or no
identifier needed?

No id needed; only for Sensor-related category: https://github.com/FedeDP/Clight/blob/master/Extra/clight.conf#L88

> Also what is "sysname" exactly? I guessed that I can add it as a new parameter
to the config section. (again, guessing that it's ok, should be documented)
I also renamed the input file after it (again, guessing! is this the right way?)

I do not understand this part sorry, what do your refer to?

> I was also assuming that I need to configure the integer range as well but
could not find it in https://github.com/FedeDP/Clightd/wiki/Sensors . However
that page talks about "maximum threshold". I guessed that this was confused
with be input range maximum and not some threshold (because otherwise - threshold
for what??).
Now it seems to work when m and M set to match my sensor readings, now I get the
'sad' value scaled properly from 0 to 1.

Wiki says for "m": `if sensor reading is below this threshold, it will be set to this value.` Is this not clear?
Same goes for 'M'.

> So far so good. But still no DDCCI activity happening.

What does `cmake -L` say in clightd build folder?
Example output:
```
cmake -L

-- Cache values
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_INSTALL_PREFIX:PATH=/usr
ENABLE_DDC:BOOL=1
ENABLE_DPMS:BOOL=1
ENABLE_GAMMA:BOOL=1
ENABLE_SCREEN:BOOL=1
ENABLE_YOCTOLIGHT:BOOL=1
SYSTEMD_SERVICE_DIR:PATH=lib/systemd/system
WAYLAND_SCANNER_EXECUTABLE:FILEPATH=/usr/bin/wayland-scanner
```

Also please note that 
> busctl call org.clightd.clightd /org/clightd/clightd/Screen

Screen module offers a way to check screen-emitted brightness, ie: it is a stupid way to allow clight to correct ambient brightness value given your screen emitted brightness. It has nothing to do with BACKLIGHT management (that is managed by backlight module indeed).

> PS: conf file in current form:

What is sysname? That won't be read by clight; you should provide a "devname".  
You should not add any key to clight conf (it won't be read).  
Note that you can leave it empty and it will use first sensor that clightd finds.

EDIT:

> while I was playing with clight.conf, it seems that the clightd was outputing some messages:
    : Expected a=b format.
This is not helpful if this only goes to hidden output of the daemon. What was the offending keyword?

You were probably setting wrong Sensor settings string.  
Btw i just pushed some small updates to clight conf file to clear up some details.

**Comment by FedeDP** [comment]
Closing. Feel free to reopen this if you encounter more issues.
