### ISSUE TITLE
Install into LIBEXECDIR

### ISSUE THREAD

**Issue by ferki** [FedeDP/Clightd#52]
As part of my efforts to package clightd for Gentoo in my overlay, I had to apply a small patch to make sure that `clightd` itself is installed into `LIBEXECDIR` instead of `LIBDIR` (`/usr/libexec` vs `/usr/lib64`) in order to be consistent with the file system layout.

I imagine this would also be useful for other downstream packagers as well, so I wondered if it's something you would consider merging upstream? Of course, I'd be happy to share the patch in the form of a follow-up PR :)

**Comment by FedeDP** [comment]
Thank you very much for your input! I'll gladly accept your PR!
Thanks!

**Comment by ferki** [comment]
Thanks for the merge too, @FedeDP! :)
