### ISSUE TITLE
yellowish adjustment after dark?

### ISSUE THREAD

**Issue by cryoguy** [FedeDP/Clightd#54]
I have been using Clightd for a couple of years.  My screen turned yellowish after sunset after the recent update. Is there a way to fix it in the config setting?

**Comment by FedeDP** [comment]
Hi! Recently Clightd gained support for Wlroots-based compositors gamma adjustments; are you on sway / any other wlroots-based wayland compositor?

Btw i guess you are talking about Clight here, aren't you? 

EDIT: if you are indeed referring to clight, you can just uncomment `disabled = true` in clight.conf:
https://github.com/FedeDP/Clight/blob/master/Extra/clight.conf#L137

**Comment by cryoguy** [comment]
Thanks! I meant `clight` and `disabled = true` fixed it.

**Comment by FedeDP** [comment]
Out of curiosity, are you using sway?

**Comment by cryoguy** [comment]
No, I have been using xfce.
