### ISSUE TITLE
Clightd doesn't start automatically

### ISSUE THREAD

**Issue by ferki** [FedeDP/Clightd#55]
I got used to clightd D-Bus service starting automatically when I execute clight from `~/.xinitrc` upon entering my desktop environment. Unfortunately it seems like it can't autostart anymore.

Based on my quick check, I've found 2a32d012e30772d1b5108be381e7884f01fb05d0 which dropped the `DAEMON_DIR` variable, but it seems like not every use of it has been cleaned up. At least `Scripts/org.clightd.clightd.service` still used it for its `Exec` line, but it's now replaced with an empty value:

```
[D-BUS Service]
Name=org.clightd.clightd
Exec=/clightd
User=root
SystemdService=clightd.service
```

Following the spirit of the above commit, replacing `@DAEMON_DIR@` with `@CMAKE_INSTALL_FULL_LIBEXECDIR@` in the source fixes my problem. I can send a PR about that soon.

**Comment by FedeDP** [comment]
Hi! Thanks for opening the PR!
That is plain stupid as i was sure i fixed the variable usage in service file...i must have forgot to commit it though.
Thank you very much for the PR, very appreciated! 
Will release a new version soon with the fix!

**Comment by ferki** [comment]
Thanks for the quick feedback and merge! :tada:

**Comment by FedeDP** [comment]
And the quick release :D
Thank you!
