### ISSUE TITLE
Clight stopped working with X11 (Fedora 33)

### ISSUE THREAD

**Issue by perceival** [FedeDP/Clightd#57]
[iglo.txt](https://github.com/FedeDP/Clightd/files/5826938/iglo.txt)

Due to NVidia drivers I had to move from Wayland to X11. Unfortunately Clight stopped working along the process.
Any hint? Here is a log.

**Comment by FedeDP** [comment]
Hi! It seems like clight is working fine; but it finds a super low ambient brightness:
> Captured [5/5] from '/dev/video0'. Ambient brightness: 0.007843.
Ambient brightness: 0.008 -> Backlight pct: 0.000.

Is this normal? Can you check that your webcam is working fine?
Then, can you try a quick:
`busctl call org.clightd.clightd /org/clightd/clightd/Sensor org.clightd.clightd.Sensor Capture "sis" "" 5 ""`

eg: in my case, it returns:
> sad "/dev/video0" 5 0.990907 0.990572 0.990161 0.980002 0.974617

Thank you!

**Comment by FedeDP** [comment]
Hi! Any news on this?

**Comment by perceival** [comment]
Seems to be working although not always. For a few days I am not going to have that particular laptop. Will update then.

**Comment by FedeDP** [comment]
Thank you!

**Comment by FedeDP** [comment]
Closing! Feel free to reopen it if you've got more info ;)
