### ISSUE TITLE
Dependencies used but not checked for

### ISSUE THREAD

**Issue by lgbaldoni** [FedeDP/Clightd#60]
Namely [dbus-1](https://github.com/FedeDP/Clightd/blob/master/CMakeLists.txt#L116) and [systemd](https://github.com/FedeDP/Clightd/blob/master/CMakeLists.txt#L144). This can lead to cmake errors not easy to trace.

**Comment by FedeDP** [comment]
Hi! Thanks for opening this bug report and relative PR!
I will comment on it. Thank you again!
