### ISSUE TITLE
compilation error, undefined ref to « libusb_set_option »

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clightd#63]
Hello

I don't know anything about C language and compilation. I only know to build I must execute cmake, make, make install.

I try to build 4.0 version of Clightd for openSuse 15.2. I get an error.

It is too techie for me. If you can help I will be glad. Thanks.

* Building clightd
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for modules 'libudev;libmodule>=5.0.0'
--   Found libudev, version 234
--   Found libmodule, version 5.0.1
-- Checking for module 'polkit-gobject-1'
--   Found polkit-gobject-1, version 0.116
-- Checking for one of the modules 'libelogind;libsystemd>=221'
-- Checking for modules 'x11;xrandr'
--   Found x11, version 1.6.5
--   Found xrandr, version 1.5.1
-- GAMMA support enabled
-- Checking for modules 'x11;xext'
--   Found x11, version 1.6.5
--   Found xext, version 1.3.3
-- DPMS support enabled
-- Checking for module 'x11'
--   Found x11, version 1.6.5
-- SCREEN support enabled
-- Checking for module 'ddcutil>=0.9.5'
--   Found ddcutil, version 0.9.9
-- DDC support enabled
-- Checking for module 'libsystemd'
--   Found libsystemd, version 234
-- Configuring done
-- Generating done
-- Build files have been written to: /home/roubach/rpmd/clight/construction/Clightd/build
Scanning dependencies of target clightd
[  6%] Building C object CMakeFiles/clightd.dir/src/main.c.o
[ 12%] Building C object CMakeFiles/clightd.dir/src/modules/backlight.c.o
[ 18%] Building C object CMakeFiles/clightd.dir/src/modules/bus.c.o
[ 25%] Building C object CMakeFiles/clightd.dir/src/modules/dpms.c.o
[ 31%] Building C object CMakeFiles/clightd.dir/src/modules/dpms_plugins/tty.c.o
[ 37%] Building C object CMakeFiles/clightd.dir/src/modules/dpms_plugins/xorg.c.o
[ 43%] Building C object CMakeFiles/clightd.dir/src/modules/gamma.c.o
[ 50%] Building C object CMakeFiles/clightd.dir/src/modules/idle.c.o
[ 56%] Building C object CMakeFiles/clightd.dir/src/modules/screen.c.o
[ 62%] Building C object CMakeFiles/clightd.dir/src/modules/sensor.c.o
[ 68%] Building C object CMakeFiles/clightd.dir/src/modules/sensors/als.c.o
[ 75%] Building C object CMakeFiles/clightd.dir/src/modules/sensors/camera.c.o
[ 81%] Building C object CMakeFiles/clightd.dir/src/modules/signal.c.o
[ 87%] Building C object CMakeFiles/clightd.dir/src/utils/polkit.c.o
[ 93%] Building C object CMakeFiles/clightd.dir/src/utils/udev.c.o
[100%] Linking C executable clightd
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld : /usr/lib64/gcc/x86_64-suse-linux/7/../../../../lib64/libddcutil.so : référence indéfinie vers « libusb_set_option »
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/clightd.dir/build.make:311: clightd] Error 1
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/clightd.dir/all] Error 2
make: *** [Makefile:169: all] Error 2

**Comment by promeneur** [comment]
I use this script

#!/bin/bash

git clone -b '4.0' --single-branch --depth 1 https://github.com/FedeDP/Clightd.git
cd Clightd
echo "* Building clightd"
mkdir build
cd build
cmake \
        -G "Unix Makefiles" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DENABLE_DDC=1 -DENABLE_GAMMA=1 -DENABLE_SCREEN=1 -DENABLE_DPMS=1 \
        ../
make

**Comment by promeneur** [comment]
Problem solved.

We need libusb 1.0 version 1.24

**Comment by FedeDP** [comment]
Hi! Sorry for being late here... it seems like libusb is indeed requested by libddcutil.so, that is weird; maybe you built ddcutil from scratch and then removed libusb?
Anyway, glad you solved!

**Comment by promeneur** [comment]
>> maybe you built ddcutil from scratch and then removed libusb?

No I just installed the opensuse packet.
