### ISSUE TITLE
somme errors/warning using clight

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clightd#64]
openSuse 15.2
clight 4.0, clightd 4.0

Hello

 i explore clight.

i built clightd 4.0 with this script

git clone -b '4.0' --single-branch --depth 1 https://github.com/FedeDP/Clightd.git
cd Clightd
echo "* Building clightd"
mkdir build
cd build
cmake \
        -G "Unix Makefiles" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_BUILD_TYPE="Release" \
        -DENABLE_DDC=1 -DENABLE_GAMMA=1 -DENABLE_SCREEN=1 -DENABLE_DPMS=1 \
        ../
make

Strangely when using clight I get these errors in clight.log 

(W)[17:17:15]{opts.c:189}	GAMMA forcefully disabled as Clightd was built without gamma support.
(W)[17:17:15]{opts.c:194}	SCREEN forcefully disabled as Clightd was built without screen support.

and this one

(I)[17:17:15]{main.c:134}	Clightd found, version: 4.0.
(I)[17:17:15]{upower.c:24}	Initial AC state: connected.
(W)[17:17:15]{interface.c:246}	Failed to create org.freedesktop.ScreenSaver dbus interface: Unknown error -1
(I)[17:17:15]{interface.c:247}	Fallback at monitoring requests to org.freedesktop.ScreenSaver name owner.

**Comment by FedeDP** [comment]
Hi, thanks for opening this bug report.
Can you update to latest Clight and Clightd? 

> (W)[17:17:15]{opts.c:189} GAMMA forcefully disabled as Clightd was built without gamma support.
(W)[17:17:15]{opts.c:194} SCREEN forcefully disabled as Clightd was built without screen support.

This issue is fixed in latest Clight!

> (W)[17:17:15]{interface.c:246} Failed to create org.freedesktop.ScreenSaver dbus interface: Unknown error -1
(I)[17:17:15]{interface.c:247} Fallback at monitoring requests to org.freedesktop.ScreenSaver name owner.

This is safe to ignore!

**Comment by promeneur** [comment]
clight 4.1 and 4.2 needs  systemd >= 237 but my openSuse 15.2 gets 234.

Does 4.2 need absolutely 237 ?

**Comment by promeneur** [comment]
clightd 5.1 compilation problem.

/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld : CMakeFiles/clightd.dir/src/utils/wl_utils.c.o : dans la fonction « create_anonymous_file » :
wl_utils.c:(.text+0x11f) : référence indéfinie vers « memfd_create »
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/clightd.dir/build.make:545: clightd] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/clightd.dir/all] Error 2
make: *** [Makefile:169: all] Error 2

**Comment by promeneur** [comment]
clightd 5.0 same problem.

**Comment by promeneur** [comment]
clightd 4.2 no problem

**Comment by FedeDP** [comment]
> clightd 5.1 compilation problem.

Uh, it seems like [memfd_create](https://man7.org/linux/man-pages/man2/memfd_create.2.html) appeared in glibc 2.27, but opensuse 15.2 is still at glibc 2.26: https://software.opensuse.org/package/glibc.  
Glibc 2.27 was released 3yrs ago: `glibc-2.27.tar.gz | 2018-02-01 15:38`.  
I will wrap the syscall directly on glibc < 2.27 to let it build!

> Does 4.2 need absolutely 237 ?

Yes, i can't do anything to fix this: i decided to drop support for older systemd versions as i was maintaining the code myself and it was not worth it. I am now using a couple of "new" APIs available since systemd 234 and 237.
Again, please note that systemd 237 is 3yrs old: `28 Jan 2018`.
I see that opensuse 15 uses systemd 234; let me check if i can do anything about it (ie: not using systemd 237 API).

Please wait next commits and build from git master next time both Clight and Clightd!

**Comment by promeneur** [comment]
For 5.1 compilation problem i forgot this

[ 60%] Building C object CMakeFiles/clightd.dir/src/utils/wl_utils.c.o
/home/roubach/rpmd/clight/clightd-5.1/Clightd/src/utils/wl_utils.c: In function ‘create_anonymous_file’:
/home/roubach/rpmd/clight/clightd-5.1/Clightd/src/utils/wl_utils.c:66:14: warning: implicit declaration of function ‘memfd_create’; did you mean ‘timerfd_create’? [-Wimplicit-function-declaration]
     int fd = memfd_create(filename, 0);

**Comment by promeneur** [comment]
about checking before compilation

* Building clightd
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for modules 'libudev;libmodule>=5.0.0;libjpeg'
--   Found libudev, version 234
--   Found libmodule, version 5.0.1
--   Found libjpeg, version 1.5.3
-- Checking for module 'polkit-gobject-1'
--   Found polkit-gobject-1, version 0.116
-- Checking for one of the modules 'libelogind;libsystemd>=221'
-- Checking for modules 'x11;xrandr;libdrm;wayland-client'
--   Found x11, version 1.6.5
--   Found xrandr, version 1.5.1
--   Found libdrm, version 2.4.100
--   Found wayland-client, version 1.18.0
-- GAMMA support enabled
-- Enabled 'wlr-gamma-control-unstable-v1' wayland client protocol
-- Checking for modules 'x11;xext;libdrm;wayland-client'
--   Found x11, version 1.6.5
--   Found xext, version 1.3.3
--   Found libdrm, version 2.4.100
--   Found wayland-client, version 1.18.0
-- DPMS support enabled
-- Enabled 'org_kde_kwin_dpms' wayland client protocol
-- Checking for module 'x11'
--   Found x11, version 1.6.5
-- SCREEN support enabled
-- Enabled 'wlr-screencopy-unstable-v1' wayland client protocol
-- Checking for module 'ddcutil>=0.9.5'
--   Found ddcutil, version 0.9.9
-- DDC support enabled
-- YOCTOLIGHT support disabled
-- Checking for module 'libsystemd'
--   Found libsystemd, version 234
-- Configuring done
-- Generating done

**Comment by promeneur** [comment]
Thanks for helping me. I wait for the  latest versions with impatience.

Thanks

**Comment by FedeDP** [comment]
> Thanks for helping me. I wait for the latest versions with impatience.

No problem sir! Ok, current Clight and Clightd master should build on your distro; let me know!

**Comment by promeneur** [comment]
Latest version (03/03/2021) of clight and clightd
compilation ok.
run no success.

(I)[23:12:30]{keyboard.c:71}	Keyboard backlight calibration unsupported.
(W)[23:12:30]{interface.c:396}	Failed to create org.freedesktop.ScreenSaver dbus interface: Unknown error -1
(I)[23:12:30]{interface.c:397}	Fallback at monitoring requests to org.freedesktop.ScreenSaver name owner.
(I)[23:12:30]{upower.c:95}	Not a laptop device. Killing UPower module.
(W)[23:12:30]{upower.c:45}	Failed to retrieve AC state; fallback to ON_AC and OPEN lid.
(W)[23:12:30]{location.c:100}	Error loading from cache file.

Yes it is a PC not a laptop but with clight 4.0 and clightd 4.2 brightness management and location was ok.

**Comment by promeneur** [comment]
i kill clight
then
in konsole i execute clight
then i get these messages

Keyboard backlight calibration unsupported.
Failed to create org.freedesktop.ScreenSaver dbus interface: Unknown error -1
Fallback at monitoring requests to org.freedesktop.ScreenSaver name owner.
Not a laptop device. Killing UPower module.
Failed to retrieve AC state; fallback to ON_AC and OPEN lid.
Error loading from cache file.
New location received: 44.86, -0.58.
Next alarm due to: Thu Feb  4 07:51:00 2021
Normal transition to 4000 gamma temp.
Ambient brightness: 0.304 -> Backlight pct: 0.476.

With clight 4.0 and clightd 4.2 i did not get these messages

Not a laptop device. Killing UPower module.
Failed to retrieve AC state; fallback to ON_AC and OPEN lid.
Error loading from cache file.

**Comment by promeneur** [comment]
Here is the state of clight by capturing the tab of clight-gui

![sensor](https://user-images.githubusercontent.com/240424/106855480-48226d80-66bd-11eb-9086-c53a9e82b7dd.png)
![backlight](https://user-images.githubusercontent.com/240424/106855482-48bb0400-66bd-11eb-8e9c-9ff3f84e8e0b.png)
![daytime](https://user-images.githubusercontent.com/240424/106855485-49539a80-66bd-11eb-9099-115e36960368.png)
![dimmer](https://user-images.githubusercontent.com/240424/106855486-49539a80-66bd-11eb-9d29-edf98300bc37.png)
![gamma](https://user-images.githubusercontent.com/240424/106855488-49ec3100-66bd-11eb-9a9c-3d1a45ca3e19.png)
![info](https://user-images.githubusercontent.com/240424/106855489-49ec3100-66bd-11eb-9f2c-3441d4e30b1f.png)
![keyboard](https://user-images.githubusercontent.com/240424/106855490-49ec3100-66bd-11eb-87b1-45f249c8ef7c.png)
![screen_comp](https://user-images.githubusercontent.com/240424/106855491-4a84c780-66bd-11eb-8012-fb5fb94eb965.png)

**Comment by FedeDP** [comment]
> With clight 4.0 and clightd 4.2 i did not get these messages
Not a laptop device. Killing UPower module.
Failed to retrieve AC state; fallback to ON_AC and OPEN lid.

It is fine: it means that, as you are on a desktop pc, it avoids wasting resources polling on upower AC state.
> Error loading from cache file.

This is just a warning; it seems it couldn't find a proper location cache file, nothing to worry about.

Glad you finally could build it!

**Comment by promeneur** [comment]
Thanks for all
