### ISSUE TITLE
[Wayland] gamma changes sporadic 

### ISSUE THREAD

**Issue by nullobsi** [FedeDP/Clightd#65]
Sometimes, the change in gamma will disappear/flash.

I was doing some debugging and it seems that the gamma manager is closed in wl.c under the Gamma module, but I don't know if that's different from a connection.

**Comment by FedeDP** [comment]
Hi! As you can read here: https://github.com/FedeDP/Clightd/blob/master/src/modules/gamma_plugins/wl.c#L134, it seems like wlroots keeps the screen temperature until a wl_display connection is active.
Indeed, Clightd does not close the connection.
Thus i see 2 possibilities:  
* Clightd crashes and is restarted by Clight (dbus activated)
* Sway closes the display connection after some idle time (as gamma temperature is automatically set by Clight during the morning and during the evening, thus lots of time passes in between, may be sway kills the conneciton even if Clightd keeps a reference on it)

Can you check if Clightd crashed?

**Comment by nullobsi** [comment]
i know clightd does not crash; i ran it under a debugger, and it still caused weird gamma changes...

it's very random, so I'm not sure what the root of the issue is. it could be something with Sway. sometimes the screen will flash the default gamma for a frame, then go back to the set gamma; other times it will reset the gamma completely.

**Comment by nullobsi** [comment]
clight-gui calls on the Clightd dbus in order to get/recieve events on the current gamma change

i think this may have something to do with the issue; perhaps two Clightd clients trying to access the same Wayland display through Clightd is causing some issues?

**Comment by nullobsi** [comment]
removing code from clight-gui that references Clightd/Gamma makes no difference; sometimes the gamma change simply goes away

**Comment by FedeDP** [comment]
> i think this may have something to do with the issue; perhaps two Clightd clients trying to access the same Wayland display through Clightd is causing some issues?

Clightd does indeed cache open wl_display connections and reuses them for any client that makes a request, even for cross-module requests, eg:
* a gamma Set opens a new display connection on let's say WAYLAND_DISPLAY wayland-0
* a dpms Set requires wayland-0 display; a connection has been cached -> dpms will use again same connection

> removing code from clight-gui that references Clightd/Gamma makes no difference; sometimes the gamma change simply goes away

As expected. I feel this is a wlroots issue, or at least i am mismanaging something in Clightd. 
Can you test with eg: https://gitlab.com/chinstrap/gammastep if it has same issue?
Thank you!

**Comment by nullobsi** [comment]
I tested it for a bit, and gammastep doesn't make the gamma flicker. However using clight, sometimes it will flicker/stop (opening clight-gui, just at random)

**Comment by nullobsi** [comment]
it also seems calling Get on clightd wayland causes the gamma to reset

**Comment by FedeDP** [comment]
> (opening clight-gui, just at random)

Does it happen only while opening clight-gui?

> it also seems calling Get on clightd wayland causes the gamma to reset

Thanks, will investigate!
Btw thank you for your testing!

**Comment by nullobsi** [comment]
It doesn't just happen when opening clight-gui; that happens because clight-gui calls Get on clightd

but, with clight running, it will randomly drop the gamma... it seems using busctl directly on clightd and not touching it has no issues

**Comment by FedeDP** [comment]
> it seems using busctl directly on clightd and not touching it has no issues

argh that makes it harder to debug; will try anyway.

> but, with clight running, it will randomly drop the gamma

Is this gamma drop related to clight-gui calling Get on Clightd or completely random? (btw out of curiosity, why are you calling Clightd directly?)
Thanks!

**Comment by nullobsi** [comment]
here's a bit of a better description 

scenario 1:
- only run clightd
- use busctl to call Set
- gamma persists, even through multiple Set calls

scenario 2:
- run clight and clightd
- gamma is set automatically
- gamma sometimes flashes/turns off

in both, calling Get on clightd, either through clight-gui or busctl, causes the gamma to disappear

**Comment by nullobsi** [comment]
Also, clight gui calls clightd directly to obtain the gamma temperature when it is opened, and then hooks to the Changed signal on gamma.

**Comment by FedeDP** [comment]
> scenario 2:
>
>   run clight and clightd
>    gamma is set automatically
>    gamma sometimes flashes/turns off
>
> in both, calling Get on clightd, either through clight-gui or busctl, causes the gamma to disappear

Thank you! This will help me isolate the problem!

> Also, clight gui calls clightd directly to obtain the gamma temperature when it is opened, and then hooks to the Changed signal on gamma.

Why don't you use `Temp` clight property? https://github.com/FedeDP/Clight/wiki/Api#read-only-bus-properties
It also emits changes!

**Comment by nullobsi** [comment]
You're welcome! But thank you for debugging this.

> Why don't you use Temp clight property?

that sounds like a good idea, I'll add it to my todo list :)

**Comment by FedeDP** [comment]
> that sounds like a good idea, I'll add it to my todo list :)

Does new clight-gui that does no more call Clightd Gamma.Get helps?

**Comment by nullobsi** [comment]
Unfortunately it did not. While it did remove the launch issue, it still randomly went away.

**Comment by FedeDP** [comment]
Hi! Can you test with attached patch?
Thank you :)
[clightd_wl.txt](https://github.com/FedeDP/Clightd/files/5974397/clightd_wl.txt)

I am trying to register the wl_display fd and dispatch any event it receives. Maybe this will keep the connection alive!

**Comment by FedeDP** [comment]
I should have found the issue: dpms protocol on wayland was segfaulting clightd were not supported (it is only supported by kwin... so on sway it crashed clightd).
I am testing and i will push a fix!

**Comment by FedeDP** [comment]
Should be fixed now!

**Comment by nullobsi** [comment]
it appears it is working fine! thank you for fixing it :)
