### ISSUE TITLE
Constant logging about busy device

### ISSUE THREAD

**Issue by mnussbaum** [FedeDP/Clightd#72]
Hi there, I've noticed that clightd seems to constantly log the following on my system `SetMaster: Device or resource busy`.  Despite the logging clight and clightd seem to be functioning correctly. This is with clightd 5.3 and clight 4.5. Is this expected behavior? If so is there any way to decrease the logging?

Happy to provide any more info I can to help debug. Thanks!

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue! 
On which system/DE?
Are gamma and dpms adjustments working in Clight?
Thank you!

**Comment by mnussbaum** [comment]
This is with sway-git and wlroots-git compiled as of a few days ago, on arch linux. What would be the best way to test if gamma and DPMS adjustments are working? Backlight changes are definitely working correctly via `IncBl` through dbus. Thanks for your help!

**Comment by FedeDP** [comment]
I guess it is related to DPMS that is not supported by sway (Clightd implements a wayland protocol that is right now only used by kde plasma; unfortunately it is the only DPMS wayland protocol out there!).
Thus, Clightd fallbacks to try "drm" method, and fails.
If this is the case, it is safe to be ignored.
You can check it by leaving your pc idle for eg: 45mins (or whatever dpms timeout you set in Clight) and see if the line is then triggered.

**Comment by FedeDP** [comment]
Closing for now; feel free to reopen it if you have any news!
