### ISSUE TITLE
Missing build deps in wiki for Fedora

### ISSUE THREAD

**Issue by NICHOLAS85** [FedeDP/Clightd#78]
I found the following two were also needed to build Clightd in Fedora 34: `polkit-devel` `dbus-devel`

**Comment by FedeDP** [comment]
Hi! Thanks for letting me know :)
I will update wiki asap!

**Comment by FedeDP** [comment]
On a second thought, Clightd shouldn't depend upon those libraries: it uses sd-bus from systemd for dbus API, and polkit api is never called (it is only invoked through dbus). 
Are you sure Clightd isn't building without those?

**Comment by NICHOLAS85** [comment]
Yea I get the following two build errors until I installed those dependencies:
```make
-- Checking for module 'polkit-gobject-1'
--   Package 'polkit-gobject-1', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:556 (message):
A required package was not found
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPkgConfig.cmake:778 (_pkg_check_modules_internal)
CMakeLists.txt:28 (pkg_check_modules)
```
```make
-- Checking for module 'dbus-1'
--   Package 'dbus-1', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:556 (message):
A required package was not found
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPkgConfig.cmake:778 (_pkg_check_modules_internal)
CMakeLists.txt:29 (pkg_check_modules)
```

https://rpmfind.net/linux/rpm2html/search.php?query=pkgconfig(polkit-gobject-1)
https://rpmfind.net/linux/rpm2html/search.php?query=pkgconfig(dbus-1)

**Comment by FedeDP** [comment]
You're right! I added them to the wiki page!
Sorry, i could not remember...they are only used as build deps though!
