### ISSUE TITLE
Can't set external monitor.

### ISSUE THREAD

**Issue by MariasStory** [FedeDP/Clightd#79]
Hi authors,
Thank you for the cool solution.

I would like to adjust the backlight for external monitor.
But, `clightd` only detects one device, the notebook monitor:
```
busctl call org.clightd.clightd /org/clightd/clightd/Backlight org.clightd.clightd.Backlight GetAll "s" ""
===
a(sd) 1 "amdgpu_bl0" 0.0509804
```
I am using `xrandr`  with `--brightness` on `HDMI-A-0`:
```
xrandr
===
eDP connected 1366x768+244+1080 ...
...
HDMI-A-0 connected primary 1920x1080+0+0 ...
...
```
How can I set backlight for `HDMI-A-0`?

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue 
Did you built clightd with ddc support? It requires ddcutil C library installed!

EDIT: have a look at: https://github.com/FedeDP/Clightd/wiki/Build#build-time-switches

**Comment by MariasStory** [comment]
Hi @FedeDP,
I am using:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=clightd-git

With `-DENABLE_DDC=1`.

I also installed the gui. There I also find only one device.

Can't I just use xrandr with the brightness parameter set from the camera?

I know that it would not work for wayland and it would be nice to have a universal solution.

**Comment by FedeDP** [comment]
Can you run `sudo ddcutil detect` and paste here the output?
Thank you!

**Comment by MariasStory** [comment]
Hi @FedeDP, sorry for the delay:

```
Invalid display
   I2C bus:  /dev/i2c-5
   EDID synopsis:
      Mfg id:               ORN
      Model:                CLB40B910
      Product code:         0
      Serial number:        
      Binary serial number: 0 (0x00000000)
      Manufacture year:     2014,  Week: 24
   DDC communication failed

Invalid display
   I2C bus:  /dev/i2c-7
   EDID synopsis:
      Mfg id:               BOE
      Model:                
      Product code:         1701
      Serial number:        
      Binary serial number: 0 (0x00000000)
      Manufacture year:     2015,  Week: 1
   DDC communication failed
   This is an eDP laptop display. Laptop displays do not support DDC/CI.
```

**Comment by FedeDP** [comment]
Uh :( unfortunately it seems that your monitor does not support DDC/Ci protocol, i am sorry! 😐
