### ISSUE TITLE
"Geoclue2 appears to be unsupported"

### ISSUE THREAD

**Issue by yochananmarqos** [FedeDP/Clightd#8]
I noticed the following in [`.clight.log`](https://github.com/FedeDP/Clightd/files/2303866/clight.log):

```
* User position:		Unsetted

* User setted sunrise:		Unsetted
* User setted sunset:		Unsetted

(W)[11:00:06]{location.c:112}	Geoclue2 appears to be unsupported.
(W)[11:00:06]{modules.c:86}	Error while loading Location module.
```

I set my latitude / longitude & sunrise / sunset in `~/.config/clight.conf`, so it's not that big of a deal to me but I figured I'd report it.

Also, "Unsetted" is not a word. It should be "Unset" or "Not Set"

`geoclue2`  2.4.10-1.2
`clight-git`  r391.3123b3b-1
`clightd-git`  r116.9a088b7-1
Manjaro Linux
Cinnamon 3.8.8

**Comment by FedeDP** [comment]
The issue about geoclue comes from a bug in geoclue 2.4.10. See here: https://github.com/jonls/redshift/issues/636. 
As you can see, clight handles it very well: in fact it caches latest user position before quitting; this way you are still loading your position from cached file even if geoclue could not be started/is not found.

> Also, "Unsetted" is not a word. It should be "Unset" or "Not Set"

Thanks! It will be fixed very soon on master and in next release!

Thanks for taking the time to report this issues!

**Comment by yochananmarqos** [comment]
I just updated to `geoclue2`  2.4.11-1 and now the error is slightly different:

```
(W)[08:27:36]{bus.c:321}	'clight' disallowed, no agent for UID 1000
(W)[08:27:36]{location.c:112}	Geoclue2 appears to be unsupported.
(W)[08:27:36]{modules.c:86}	Error while loading Location module.
(W)[08:27:36]{bus.c:321}	No such interface 'org.freedesktop.GeoClue2.Client' on object at path /org/freedesktop/GeoClue2/Client/1
```

I then added the following to `/etc/geoclue/geoclue.conf`:
```
[clight]
allowed=true
system=false
users=
```

Now it works:
`(I)[08:36:58]{location.c:179}	New location received: XX.XX, -XXX.XX
`

**Comment by FedeDP** [comment]
Mmmh closed too fast.  
I see that "org.freedesktop.GeoClue2.Client.DesktopId" property should be named after clight desktop file (as put in /usr/share/applications) that is "clightc" instead of "clight"; although now i got https://github.com/jonls/redshift/issues/636#issuecomment-409435222 issue (ie: it asks me every time to access user location). 
That should be "fixed" (even if it is an hack; proper fix should be provided, in my case, from kde) by the /etc/geoclue/geoclue.conf hack. If you use gnome, you do not need that hack though.

Let me know if the new commit fixed that for you (ie: try to remove the geoclue.conf hack and restart clight. If it works, we are fine. Otherwise add back the hack).

EDIT: your geoclue.conf hack should now be named "[clightc]" instead.

**Comment by FedeDP** [comment]
I can confirm that in kde i need both my new commit AND your hack (with [clightc]) to avoid being asked to access user location at every reboot. 
It will probably be added in clight README.

**Comment by yochananmarqos** [comment]
I rebuilt `clight-git` (now r393.228369b-1) and changed `[clight]` to `[clightc]` in `geoclue.conf`. After rebooting, the error is similar:
```
(W)[10:00:30]{bus.c:321}	'clightc' disallowed, no agent for UID 1000
(W)[10:00:30]{location.c:112}	Geoclue2 appears to be unsupported.
(I)[10:00:31]{location.c:78}	Location XX.XX -XXX.XX loaded from cache file!
(W)[10:00:31]{modules.c:86}	Error while loading Location module.
(W)[10:00:31]{bus.c:321}	No such interface 'org.freedesktop.GeoClue2.Client' on object at path /org/freedesktop/GeoClue2/Client/1
```

**Comment by FedeDP** [comment]
I don't really understand what's going on there.  
It should work at least like it did before (when org.freedesktop.GeoClue2.Client.DesktopId was named "clight" and in geoclue.conf you had "[clight]").
I just tried once more and it works correctly here now, even when starting clight.service manually.

**Comment by yochananmarqos** [comment]
It could have been that `geoclue2` hadn't started yet, I guess. I ended up rebooted again and now it's working.

By the way, you missed a few strings. _Set_, not _setted_. ;)
```
* User position:		Unsetted

* User setted sunrise:		Unset
* User setted sunset:		Unset

(I)[10:16:50]{gamma.c:199}	6500 gamma temp setted.
```

**Comment by FedeDP** [comment]
I'll let this issue open for some days. Feel free to close it if you do not encounter any more issue :)

**Comment by FedeDP** [comment]
> By the way, you missed a few strings. Set, not setted. ;)

Thanks! Fixed now! :)
