### ISSUE TITLE
iio device I/O error

### ISSUE THREAD

**Issue by fufexan** [FedeDP/Clightd#83]
I've tried setting the sensor to `iio:device0` based on info I've read in #34, but I get the following error.
```sh
› busctl call org.clightd.clightd /org/clightd/clightd/Sensor/Als org.clightd.clightd.Sensor Capture "sis" "" 5 ""
Call failed: Input/output error
```

The device is available, as shown here:
```sh
› busctl call org.clightd.clightd /org/clightd/clightd/Sensor/Als org.clightd.clightd.Sensor IsAvailable "s" ""
sb "/dev/iio:device0" true
```

Camera seems to work fine when issuing the first command, but I'd like to use the sensor instead. Is there anything I can do to fix it?

Some info:
- OS: NixOS Unstable
- Clightd version: 5.4

**Comment by FedeDP** [comment]
Hi! Indeed Clightd has seen some fixes for ambient light sensors, and should work fine now.
Can you try using clightd from master?

**Comment by fufexan** [comment]
Fixed, thanks!

**Comment by FedeDP** [comment]
You're welcome man! Thanks for using Clightd!
