### ISSUE TITLE
Need libusb-1.0-0-dev in Ubuntu

### ISSUE THREAD

**Issue by jdnixx** [FedeDP/Clightd#87]
Just built successfully but it gave me a `No package 'libusb-1.0' found`. I thought libusb-dev would've taken care of that but you have to `sudo apt install libusb-1.0-0-dev` as well. This is on Kubuntu 21.10, just thought I should put it in here if someone else gets the same error.

**Comment by FedeDP** [comment]
Uh! Thanks for pointing it out! I will update the wiki page! :rocket:
