### ISSUE TITLE
Not able to detect ALS on ThinkPad X1 Yoga Gen 5

### ISSUE THREAD

**Issue by jclsn** [FedeDP/Clightd#89]
Hi Federico,

I know this is not a clightd issue really, but I can't seem to activate the ALS on this device. On my previous X380 Yoga it worked quite well. I wonder why, since it is a pretty popular device. I already tried the dbus command from the wiki, but it doesn't work.

Can you maybe assist me on trying to get this to work?

**Comment by FedeDP** [comment]
Hi! Sure we can!
Can you share the output from the clightd dbus command in the wiki?
Thanks!

**Comment by jclsn** [comment]
Thank you. It says

```
busctl call org.clightd.clightd /org/clightd/clightd/Sensor/Als org.clightd.clightd.Sensor Capture "sis" "" 5 ""
Call failed: No such device
```
I am pretty sure that this device has this sensor though, since it is listed in the [specifications document ](https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_X1_Yoga_Gen_5/ThinkPad_X1_Yoga_Gen_5_Spec.PDF) from Lenovo.

**Comment by FedeDP** [comment]
Do you have any file under /sys/bus/iio/devices/ folder?

**Comment by jclsn** [comment]
Yes, but it seems only the gyro sensor is there

```
❯ ls /sys/bus/iio/devices
iio:device0  iio:device1  iio:device2  trigger0  trigger1  trigger2
❯ ls /sys/bus/iio/devices/iio:device0
buffer                   in_angl0_label  in_angl2_label      in_angl_sampling_frequency  scan_elements
buffer0                  in_angl0_raw    in_angl2_raw        in_angl_scale               subsystem
current_timestamp_clock  in_angl1_label  in_angl_hysteresis  name                        trigger
dev                      in_angl1_raw    in_angl_offset      power                       uevent
❯ ls /sys/bus/iio/devices/iio:device1
buffer                   in_accel_hysteresis          in_accel_x_raw  power          uevent
buffer0                  in_accel_offset              in_accel_y_raw  scan_elements  
current_timestamp_clock  in_accel_sampling_frequency  in_accel_z_raw  subsystem      
dev                      in_accel_scale               name            trigger        
❯ ls /sys/bus/iio/devices/iio:device2
buffer                   in_anglvel_hysteresis          in_anglvel_x_raw  power          uevent
buffer0                  in_anglvel_offset              in_anglvel_y_raw  scan_elements  
current_timestamp_clock  in_anglvel_sampling_frequency  in_anglvel_z_raw  subsystem      
dev                      in_anglvel_scale               name              trigger 
```

**Comment by jclsn** [comment]
Hmm I guess it is not activated in the Manjaro kernel then, is it?

**Comment by FedeDP** [comment]
Perhaps it is not supported yet by the Linux kernel?
I am trying to find some info:)

**Comment by jclsn** [comment]
That would be weird. This is not the latest X1 Yoga. The Gen 7 was just released I think. Unfortunately the sensor's name is not contained in the spec.

**Comment by jclsn** [comment]
I asked for the sensor's name in the Lenovo forums. We'll see

https://forums.lenovo.com/t5/ThinkPad-X-Series-Laptops/What-is-the-name-of-the-ALS-sensor-installed-in-the-X1-Yoga-Gen-5/m-p/5169231

I hope the Manjaro team just hasn't compiled the kernel with the required module.

**Comment by jclsn** [comment]
Guess it doesn't have a sensor. So closing...

**Comment by FedeDP** [comment]
That's unfortunate 😦

**Comment by jclsn** [comment]
So I asked the support and they said it has an ALS, but it only works on Windows. I asked them for the model. No response so far. They also said I couldn't see the ALS, because it was installed on the mainboard. No idea how it would sense light there, but well :D
